
#Para compilar y crear todos los objetos 
all: compilar


################################################
#todos los ejecutables creados al momento de compilar
ejecutables: L3.1 L3.2 L3.3 L3.4 L3.5 L3.6 L3.7 L4.1 L4.1 L4.2 L4.3 L4.4 L4.5 L4.6 L4.7 L4.8 L4.9 L4.10 L4.11 L4.12 L4.13 L4.14 L4.15 L5.1 L5.2 L5.3 L5.4 L5.5 L5.6 L5.7 L5.8 L5.9 L5.10 L5.11 L5.12

################################################

#Donde se encuentran todos los src para compilar 
compilar: Listing3.1.o Listing3.2.o Listing3.3.o Listing3.4.o Listing3.5.o Listing3.6.o Listing3.7.o Listing4.1.o Listing4.2.o Listing4.3.o Listing4.4.o Listing4.5.o Listing4.6.o Listing4.7.o Listing4.8.o Listing4.9.o Listing4.10.o Listing4.11.o Listing4.12.o Listing4.13.o  Listing4.14.o Listing4.15.o Listing5.1.o Listing5.2.o Listing5.3.o Listing5.4.o Listing5.5.o Listing5.6.o Listing5.7.o Listing5.8.o Listing5.9.o Listing5.10.o Listing5.11.o Listing5.12.o
	g++ Listing3.1.o -o L3.1
	g++ Listing3.2.o -o L3.2
	g++ Listing3.3.o -o L3.3
	g++ Listing3.4.o -o L3.4
	g++ Listing3.5.o -o L3.5
	g++ Listing3.6.o -o L3.6
	g++ Listing3.7.o -o L3.7

	g++ Listing4.1.o -o L4.1
	g++ Listing4.2.o -o L4.2
	g++ Listing4.3.o -o L4.3
	g++ Listing4.4.o -o L4.4
	g++ Listing4.5.o -o L4.5
	g++ Listing4.6.o -o L4.6
	g++ Listing4.7.o -o L4.7
	g++ Listing4.8.o -o L4.8
	g++ Listing4.9.o -o L4.9
	g++ Listing4.10.o -o L4.10
	g++ Listing4.11.o -o L4.11
	g++ Listing4.12.o -o L4.12
	g++ Listing4.13.o -o L4.13
	g++ Listing4.14.o -o L4.14
	g++ Listing4.15.o -o L4.15

	g++ Listing5.1.o -o L5.1
	g++ Listing5.2.o -o L5.2
	g++ Listing5.3.o -o L5.3
	g++ Listing5.4.o -o L5.4
	g++ Listing5.5.o -o L5.5
	g++ Listing5.6.o -o L5.6
	g++ Listing5.7.o -o L5.7
	g++ Listing5.8.o -o L5.8
	g++ Listing5.9.o -o L5.9
	g++ Listing5.10.o -o L5.10
	g++ Listing5.11.o -o L5.11
	g++ Listing5.12.o -o L5.12

################################################

#Compilacion individual de cada Listing
Listing3.1.o: Listing3.1.cpp
	g++ -c Listing3.1.cpp

Listing3.2.o: Listing3.2.cpp
	g++ -c Listing3.2.cpp

Listing3.3.o: Listing3.3.cpp
	g++ -c Listing3.3.cpp

Listing3.4.o: Listing3.4.cpp
	g++ -c Listing3.4.cpp

Listing3.5.o: Listing3.5.cpp
	g++ -c Listing3.5.cpp

Listing3.6.o: Listing3.6.cpp
	g++ -c Listing3.6.cpp

Listing3.7.o: Listing3.7.cpp
	g++ -c Listing3.7.cpp

Listing4.1.o: Listing4.1.cpp
	g++ -c Listing4.1.cpp

Listing4.2.o: Listing4.2.cpp
	g++ -c Listing4.2.cpp

Listing4.3.o: Listing4.3.cpp
	g++ -c Listing4.3.cpp

Listing4.4.o: Listing4.4.cpp
	g++ -c Listing4.4.cpp

Listing4.5.o: Listing4.5.cpp
	g++ -c Listing4.5.cpp

Listing4.6.o: Listing4.6.cpp
	g++ -c Listing4.6.cpp

Listing4.7.o: Listing4.7.cpp
	g++ -c Listing4.7.cpp

Listing4.8.o: Listing4.8.cpp
	g++ -c Listing4.8.cpp

Listing4.9.o: Listing4.9.cpp
	g++ -c Listing4.9.cpp

Listing4.10.o: Listing4.10.cpp
	g++ -c Listing4.10.cpp

Listing4.11.o: Listing4.11.cpp
	g++ -c Listing4.11.cpp

Listing4.12.o: Listing4.12.cpp
	g++ -c Listing4.12.cpp

Listing4.13.o: Listing4.13.cpp
	g++ -c Listing4.13.cpp

Listing4.14.o: Listing4.14.cpp
	g++ -c Listing4.14.cpp

Listing4.15.o: Listing4.15.cpp
	g++ -c Listing4.15.cpp

Listing5.1.o: Listing5.1.cpp
	g++ -c Listing5.1.cpp

Listing5.2.o: Listing2.1.cpp
	g++ -c Listing2.1.cpp

Listing5.3.o: Listing5.3.cpp
	g++ -c Listing5.3.cpp

Listing5.4.o: Listing5.4.cpp
	g++ -c Listing5.4.cpp

Listing5.5.o: Listing5.5.cpp
	g++ -c Listing5.5.cpp

Listing5.6.o: Listing5.6.cpp
	g++ -c Listing5.6.cpp

Listing5.7.o: Listing5.7.cpp
	g++ -c Listing5.7.cpp

Listing5.8.o: Listing5.8.cpp
	g++ -c Listing5.8.cpp

Listing5.9.o: Listing5.9.cpp
	g++ -c Listing5.9.cpp

Listing5.10.o: Listing5.10.cpp
	g++ -c Listing5.10.cpp

Listing5.11.o: Listing5.11.cpp
	g++ -c Listing5.11.cpp

Listing5.12.o: Listing5.12.cpp
	g++ -c Listing5.12.cpp


############################################
#Borrar todos los objetos
clean:
	rm -rf *o compilar
############################################


#instalar los ejecutables en la direccion proporcionada en clase
install:  
	cp ejecutables /var/opt/lp3/tp1

